# -*- coding: utf-8 -*-
"""DA ASSIGNMENT-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12n9KbBNSrugdqVtFCQ31fW7vrUV4i0Qj
"""

#IMPORTING NECESSARY LIBRARIES
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyplot

#LOAD DATASETS
data = pd.read_csv('/content/drive/MyDrive/machine learning/abalone.csv')

data.info()

data.describe()

pip install matplotlib





pip install seaborn

import seaborn as sns

data.describe()

#UNIVARIATE ANALYSIS
data.hist(figsize=(20,10), grid=False, layout=(2, 4), bins = 30)

numerical_features = data.select_dtypes(include=[np.number]).columns
categorical_features = data.select_dtypes(include=[np.object]).columns

numerical_features

categorical_features

#BIVARIATE ANALYSIS
sns.pairplot(data[numerical_features])

#STATISTICAL ANALYSIS ON DATASET
data.head

data.tail

#HANDLING MISSING VALUE
data.isnull().any()

#OUTLIERS
data = pd.get_dummies(data)
dummy_data = data.copy()

data.boxplot( rot = 90, figsize=(20,5))

#CATEGORICAL COLUMN
categorical_features

#INDEPENDANT AND DEPENDANT 
x=data.iloc[:,0:5]
y=data.iloc[:,0:2]

x

y

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)



